pipeline {  //root of the pipeline
    agent any //where the pipeline run any means it will run anywindo /linux 

    tools {
        maven 'Maven-3'
     }
     
      stages {  // group of multiple task that i want perform

        stage('Build') { // single task that i want to execute automaticaly
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
    post {
        success {
            echo 'Build Successful '
        }
        failure {
            echo 'Build Failed '
        }
        always {
            echo 'Pipeline Finished '
        }
    }
     
 }